local server = require "server"
local BaseConfig = {}

BaseConfig.YuanbaoRecordType = {
	GMCMD				= 1,	-- GM命令
	Recharge			= 2,	-- 充值
	Chapter				= 3,	-- 关卡
	BagAddMaxEquipCount	= 4,	-- 扩展背包
	UseItem				= 5,	-- 使用物品
	Smelt				= 6,	-- 熔炼
	Pet					= 7,	-- 宠物
	Xianlv				= 8,	-- 仙侣
	Shop				= 9,	-- 商店
	RecordMail			= 10,	-- 后台发送邮件
	FieldBoss			= 11,	-- 野外BOSS
	FubenClear			= 12,	-- 材料副本扫荡
	CatchPet			= 13,	-- 宠物抓取
	Ride				= 14,	-- 坐骑
	Wing				= 15,	-- 翅膀
	Fairy				= 16,	-- 天仙
	Weapon				= 17,	-- 神兵
	Soul				= 18,	-- 宠物通灵
	Psychic				= 19,	-- 宠物兽魂
	Position			= 20,	-- 仙侣仙位
	Circle				= 21,	-- 仙侣法阵
	Material			= 22,	-- 材料副本
	TreasureMap			= 23,	-- 藏宝图
	HeavenFb			= 24,	-- 勇闯天庭
	WildgeeseFb			= 25,	-- 玲珑宝塔
	PublicBoss			= 26,	-- 全民BOSS
	Arena				= 27,	-- 竞技场
	TianNv				= 28,	-- 天女
	ShenBing			= 29,	-- 神兵
	Title				= 30,	-- 称号
	Skin				= 31,	-- 时装
	Vein				= 32,	-- 经脉
	Panacea				= 33,	-- 丹药
	CreateGuild			= 34,	-- 创建公会
	GuildSkill			= 35,	-- 帮会技能
	EatPeach			= 36,	-- 帮会蟠桃
	DonateWood			= 37,	-- 帮会贡献
	GuildProtector		= 38,	-- 帮会守护
	SpellsRes			= 39,	-- 法宝
	GuildRename			= 40,	-- 公会改名
	CrossTeam			= 41,	-- 组队副本
	GuildMap			= 42,	-- 帮会地图
	Task				= 43,	-- 引导任务
	TianShen			= 44,	-- 天神
	TianShenSpells		= 45,	-- 天神宝器
	Exchange			= 46,	-- 银两兑换
	Formation			= 47,	-- 阵型
	Escort				= 48,	-- 护送
	Vip					= 49,	-- VIP
	GuildBoss			= 50,	-- 帮会Boss
	Answer				= 51,	-- 答题
	DailyTask			= 52,	-- 日常
	VIPBoss				= 53,	-- VIPBOSS
	GuildMine			= 54,	-- 矿山争夺
	King				= 55,	-- 跨服争霸
	Climb				= 56,	-- 九重天
	KfBoss				= 57,	-- 跨服BOSS
	QualifyingMgr		= 58,	-- 仙道会
	EightyOneHard		= 59,	-- 八十一难
	Guildwar			= 60,	-- 帮会战
	Marry				= 61,	-- 姻缘
	Offline				= 62,	-- 离线经验
	Friend				= 63,	-- 好友
	Teachers			= 64,	-- 师徒
	SignIn				= 65,	-- 签到
	BonusMgr			= 66,	-- 系统红包
	Welfare				= 67,	-- 福利大厅
	Redeemcode			= 68,	-- 激活码
	Baby				= 69,	-- 灵童
	Guide				= 70,	-- 新手指引
	Maincity			= 71,	-- 主城
	Activity			= 72,	-- 运营活动
	Advanced			= 73,	-- 进阶奖励
	Luck				= 74,	-- 寻宝
	FuncNotice			= 75,	-- 功能预告
	Auction				= 76,	-- 拍卖行
	Invest				= 77,	-- 投资计划
	GrowFund			= 78,	-- 成长基金
	SpendGift			= 79,	-- 消费有礼
	Rename				= 80,	-- 改名
	DailyRecharge		= 81,	-- 每日充值
	PackageDiscount		= 82,	-- 折扣商店
	BabyStar			= 83,	-- 灵童命格
	Invalid				= 84,	-- 过期了
	GuildFb 			= 85, 	-- 帮会副本
	Flower				= 86,	-- 天女花辇
	Nimbus				= 87,	-- 天女灵气
	HolyPet				= 88,	-- 神兽
	Rebate				= 89,	--充值返利
	LuckTianshen		= 90,	--天神抽奖
	ChoiceRechare		= 91,	--特惠充值
	RedEquip			= 92,	--红装
	LoginGift			= 93,	--登入奖励
	Totems				= 94,	--图腾
	Guilddividend 		= 95, 	--分红
	Enhance 			= 96, 	--我要变强
	KingArena 			= 97, 	--跨服王者
	HeavenGifts 		= 98,	--天降好礼
	CashCow 			= 99, 	--摇钱树
	PositionSystem 		= 100,	--阵位系统
	HolyXinJun			= 101,	-- 星君降临
	Xianjun				= 102,	-- 星君
	Fly					= 103,	-- 人物飞升
	Recycle				= 104,	-- 物品回收
}

BaseConfig.YuanbaoRecordTypeToName = {
	[BaseConfig.YuanbaoRecordType.GMCMD] = "GMCMD",
	[BaseConfig.YuanbaoRecordType.Recharge] = "Recharge",
	[BaseConfig.YuanbaoRecordType.Chapter] = "Chapter",
	[BaseConfig.YuanbaoRecordType.BagAddMaxEquipCount] = "BagAddMaxEquipCount",
	[BaseConfig.YuanbaoRecordType.UseItem] = "UseItem",
	[BaseConfig.YuanbaoRecordType.Smelt] = "Smelt",
	[BaseConfig.YuanbaoRecordType.Pet] = "Pet",
	[BaseConfig.YuanbaoRecordType.Xianlv] = "Xianlv",
	[BaseConfig.YuanbaoRecordType.Shop] = "Shop",
	[BaseConfig.YuanbaoRecordType.Ride] = "Ride",
	[BaseConfig.YuanbaoRecordType.RecordMail] = "RecordMail",
	[BaseConfig.YuanbaoRecordType.FieldBoss] = "FieldBoss",
	[BaseConfig.YuanbaoRecordType.FubenClear] = "FubenClear",
	[BaseConfig.YuanbaoRecordType.CatchPet] = "CatchPet",
	[BaseConfig.YuanbaoRecordType.Wing] = "Wing",
	[BaseConfig.YuanbaoRecordType.Fairy] = "Fairy",
	[BaseConfig.YuanbaoRecordType.Weapon] = "Weapon",
	[BaseConfig.YuanbaoRecordType.Soul] = "Soul",
	[BaseConfig.YuanbaoRecordType.Psychic] = "Psychic",
	[BaseConfig.YuanbaoRecordType.Position] = "Position",
	[BaseConfig.YuanbaoRecordType.Circle] = "Circle",
	[BaseConfig.YuanbaoRecordType.Material] = "Material",
	[BaseConfig.YuanbaoRecordType.TreasureMap] = "TreasureMap",
	[BaseConfig.YuanbaoRecordType.HeavenFb] = "HeavenFb",
	[BaseConfig.YuanbaoRecordType.WildgeeseFb] = "WildgeeseFb",
	[BaseConfig.YuanbaoRecordType.PublicBoss] = "PublicBoss",
	[BaseConfig.YuanbaoRecordType.Arena] = "Arena",
	[BaseConfig.YuanbaoRecordType.TianNv] = "TianNv",
	[BaseConfig.YuanbaoRecordType.ShenBing] = "ShenBing",
	[BaseConfig.YuanbaoRecordType.Title] = "Title",
	[BaseConfig.YuanbaoRecordType.Skin] = "Skin",
	[BaseConfig.YuanbaoRecordType.Vein] = "Vein",
	[BaseConfig.YuanbaoRecordType.Panacea] = "Panacea",
	[BaseConfig.YuanbaoRecordType.CreateGuild] = "CreateGuild",
	[BaseConfig.YuanbaoRecordType.GuildSkill] = "GuildSkill",
	[BaseConfig.YuanbaoRecordType.EatPeach] = "EatPeach",
	[BaseConfig.YuanbaoRecordType.DonateWood] = "DonateWood",
	[BaseConfig.YuanbaoRecordType.GuildProtector] = "GuildProtector",
	[BaseConfig.YuanbaoRecordType.SpellsRes] = "SpellsRes",
	[BaseConfig.YuanbaoRecordType.GuildRename] = "GuildRename",
	[BaseConfig.YuanbaoRecordType.CrossTeam] = "CrossTeam",
	[BaseConfig.YuanbaoRecordType.TianShen] = "TianShen",
	[BaseConfig.YuanbaoRecordType.GuildMap] = "GuildMap",
	[BaseConfig.YuanbaoRecordType.Task] = "Task",
	[BaseConfig.YuanbaoRecordType.TianShen] = "TianShen",
	[BaseConfig.YuanbaoRecordType.TianShenSpells] = "TianShenSpells",
	[BaseConfig.YuanbaoRecordType.Formation] = "Formation",
	[BaseConfig.YuanbaoRecordType.Exchange] = "Exchange",
	[BaseConfig.YuanbaoRecordType.Formation] = "Formation",
	[BaseConfig.YuanbaoRecordType.Escort] = "Escort",
	[BaseConfig.YuanbaoRecordType.Vip] = "Vip",
	[BaseConfig.YuanbaoRecordType.GuildBoss] = "GuildBoss",
	[BaseConfig.YuanbaoRecordType.Answer] = "Answer",
	[BaseConfig.YuanbaoRecordType.DailyTask] = "DailyTask",
	[BaseConfig.YuanbaoRecordType.VIPBoss] = "VIPBoss",
	[BaseConfig.YuanbaoRecordType.GuildMine] = "GuildMine",
	[BaseConfig.YuanbaoRecordType.King] = "King",
	[BaseConfig.YuanbaoRecordType.Climb] = "Climb",
	[BaseConfig.YuanbaoRecordType.KfBoss] = "KfBoss",
	[BaseConfig.YuanbaoRecordType.QualifyingMgr] = "QualifyingMgr",
	[BaseConfig.YuanbaoRecordType.EightyOneHard] = "EightyOneHard",
	[BaseConfig.YuanbaoRecordType.Guildwar] = "Guildwar",
	[BaseConfig.YuanbaoRecordType.Marry] = "Marry",
	[BaseConfig.YuanbaoRecordType.Offline] = "Offline",
	[BaseConfig.YuanbaoRecordType.Friend] = "Friend",
	[BaseConfig.YuanbaoRecordType.Teachers] = "Teachers",
	[BaseConfig.YuanbaoRecordType.SignIn] = "SignIn",
	[BaseConfig.YuanbaoRecordType.BonusMgr] = "BonusMgr",
	[BaseConfig.YuanbaoRecordType.Welfare] = "Welfare",
	[BaseConfig.YuanbaoRecordType.Redeemcode] = "Redeemcode",
	[BaseConfig.YuanbaoRecordType.Baby] = "Baby",
	[BaseConfig.YuanbaoRecordType.Guide] = "Guide",
	[BaseConfig.YuanbaoRecordType.Maincity] = "Maincity",
	[BaseConfig.YuanbaoRecordType.Activity] = "Activity",
	[BaseConfig.YuanbaoRecordType.Advanced] = "Advanced",
	[BaseConfig.YuanbaoRecordType.Luck] = "Luck",
	[BaseConfig.YuanbaoRecordType.FuncNotice] = "FuncNotice",
	[BaseConfig.YuanbaoRecordType.Auction] = "Auction",
	[BaseConfig.YuanbaoRecordType.Invest] = "Invest",
	[BaseConfig.YuanbaoRecordType.GrowFund] = "GrowFund",
	[BaseConfig.YuanbaoRecordType.SpendGift] = "SpendGift",
	[BaseConfig.YuanbaoRecordType.Rename] = "Rename",
	[BaseConfig.YuanbaoRecordType.DailyRecharge] = "DailyRecharge",
	[BaseConfig.YuanbaoRecordType.PackageDiscount] = "PackageDiscount",
	[BaseConfig.YuanbaoRecordType.BabyStar] = "BabyStar",
	[BaseConfig.YuanbaoRecordType.Invalid] = "Invalid",
	[BaseConfig.YuanbaoRecordType.GuildFb] = "GuildFb",
	[BaseConfig.YuanbaoRecordType.Flower] = "Flower",
	[BaseConfig.YuanbaoRecordType.Nimbus] = "Nimbus",
	[BaseConfig.YuanbaoRecordType.HolyPet] = "HolyPet",
	[BaseConfig.YuanbaoRecordType.Rebate] = "Rebate",
	[BaseConfig.YuanbaoRecordType.LuckTianshen] = "LuckTianshen",
	[BaseConfig.YuanbaoRecordType.ChoiceRechare] = "ChoiceRechare",
	[BaseConfig.YuanbaoRecordType.RedEquip] = "RedEquip",
	[BaseConfig.YuanbaoRecordType.LoginGift] = "LoginGift",
	[BaseConfig.YuanbaoRecordType.Totems] = "Totems",
	[BaseConfig.YuanbaoRecordType.Guilddividend] = "Guilddividend",
	[BaseConfig.YuanbaoRecordType.Enhance] = "Enhance",
	[BaseConfig.YuanbaoRecordType.HeavenGifts] = "HeavenGifts",
	[BaseConfig.YuanbaoRecordType.KingArena] = "KingArena",
	[BaseConfig.YuanbaoRecordType.CashCow] = "CashCow",
	[BaseConfig.YuanbaoRecordType.PositionSystem] = "PositionSystem",
	[BaseConfig.YuanbaoRecordType.HolyXinJun] = "HolyXinJun",
	[BaseConfig.YuanbaoRecordType.Xianjun] = "Xianjun",
	[BaseConfig.YuanbaoRecordType.Fly] = "Fly",
	[BaseConfig.YuanbaoRecordType.Recycle] = "Recycle",
}

--属性记录
--server.baseConfig.AttrRecord.
BaseConfig.AttrRecord = {
	EquipBase = 1, 	--装备基础属性
	EquipSuit = 2, 	--装备套装达人
	EquipForge = 3, 	--装备锻造
	EquipForgeSuit = 4, 	--锻造大师
	EquipRedInject = 5, 	--红装注灵
	EquipRedInjectSuit = 6, --红装注灵共鸣
	EquipRedSuit = 7, 	--红装套装
	PetBase = 8, 	--宠物基础属性
	PetGift = 9, 	--宠物资质
	PetFly 	= 10, 	--宠物飞升
	GuildSkill = 11, 	--帮会技能
	Vein = 12, 	--经脉
	Panacea = 13, 	--丹药
	Skin = 14, 	--时装
	Title = 15, 	--称号
	BabyBase = 16,	--灵通基础
	BabyGift = 17,
	BabyStar = 18,
	Brother = 19,
	Clothes = 20,
	DailyTask = 21,
	Formation = 22,
	GuildProtector = 23,
	House = 24,
	EffectBase = 25,
	LevelUp = 26,
	SpellsRes = 27,
	Template = 28,
	Tiannv = 29,
	Tianshen = 30,
	TianshenSpells = 31,
	Xianlv = 32,
	TianshenFly = 33,
	Xianjun = 34,
	Fly 	= 35,
}

server.SetCenter(BaseConfig, "baseConfig")
return BaseConfig
